const ACTION_TYPES = {
  UPDATE_USER_DATA: "UPDATE_USER_DATA",
  LOG_OUT_USER: "LOG_OUT_USER",
  UPDATE_SERVICES: "UPDATE_SERVICES",
  SET_FILTER_VALUE: "SET_FILTER_VALUE",
  SET_FILTER_PROPS: "SET_FILTER_PROPS",
  CLEAR_ALL_FILTER_PROPS: "CLEAR_ALL_FILTER_PROPS",
  SEND_MESSAGE: "SEND_MESSAGE",
  LOAD_EARLIER_MESSAGES: "LOAD_EARLIER_MESSAGES",
  LOAD_EARLIER_START: "LOAD_EARLIER_START",
  SET_IS_TYPING: "SET_IS_TYPING",
};

export default ACTION_TYPES;
