import {
  Filters,
  PaymentStatus,
  ReduxState,
  UserType,
} from "~src/@types/types";

const INITIAL_STATE: ReduxState = {
  user: {
    id: "",
    userType: UserType.USER,
    username: "",
    email: "",
    phoneNumber: "",
    locations: [],
    profilePicture: null,
    isEmailVerified: false,
    isPhoneVerified: false,
    isActive: false,
    isLoggedIn: false,
    createdAt: undefined,
  },
  // services: [],
  // bookings: [],
  filters: {
    [Filters.SERVICE_CATEGORY]: {
      id: "",
      name: "",
    },
  },
  chat: {
    messages: [],
    step: 0,
    loadEarlier: true,
    isLoadingEarlier: false,
    isTyping: false,
  },
  booking: {
    id: "",
    providerId: "",
    userId: "",
    serviceId: "",
    createdAt: "",
    updatedAt: "",
    location: {
      name: "",
      location: {
        latitude: 0,
        longitude: 0,
        altitude: null,
        accuracy: null,
        altitudeAccuracy: null,
        heading: null,
        speed: null,
      },
    },
    paymentMethodObject: {
      id: "",
      name: "",
      extraData: undefined,
    },
    paymentStatus: PaymentStatus.NOT_PAID,
    customerName: "",
    customerEmail: "",
    customerPhone: "",
    scheduledDate: "",
    scheduledTime: "",
    notes: "",
    attachments: [],
    bookingStates: [],
  },
  serviceInCreation: {
    id: "",
    providerId: "",
    name: "",
    category: {
      id: "",
      name: "",
      description: undefined,
      image: undefined,
    },
    location: {
      name: "",
      address: undefined,
      location: {
        latitude: 0,
        longitude: 0,
        altitude: null,
        accuracy: null,
        altitudeAccuracy: null,
        heading: null,
        speed: null,
      },
    },
    coverImage: "",
    email: null,
    createdAt: "",
    isAvailable: false,
  },
};

export default INITIAL_STATE;
